name: Bug melden [DE]
description: Einen Bug melden.
labels:
- Bug
body:
- type: markdown
  attributes:
    value: 'Danke, dass du dir Zeit nimmst, diesen Bugreport auszufüllen.

      Fülle den Bugreport bitte aus und versuche, so genau wie möglich zu beschreiben,
      was passiert ist. Wenn du den Fehler reproduzieren kannst, beschreibe bitte,
      wie du das tust.

      '
- type: dropdown
  id: mod-version
  attributes:
    label: Version
    description: Welche Enhanced Livestock Version verwendest du?
    options:
    - '0'
    - 1.0.0.0
    - 1.1.0.0-beta1
    default: 2
  validations:
    required: true
- type: dropdown
  id: game-version
  attributes:
    label: Spielversion
    description: Welche Spielversion verwendest du?
    options:
    - 1.4.0.0
    - 1.5.0.0
    - 1.5.0.1
    - 1.6.0.0
    - 1.7.0.1
    - 1.7.0.2
    - 1.8.0.1
    - 1.9.0.1
    - 1.10.0.0
    - 1.14.1.0
    - 1.15.0.0
    default: 10
  validations:
    required: true
- type: dropdown
  id: spmp
  attributes:
    label: SP/MP
    description: Hast du den Bug im SP oder MP?
    options:
    - SP (Singleplayer)
    - MP (Multiplayer)
    default: 0
  validations:
    required: true
- type: textarea
  id: what-happened
  attributes:
    label: Was ist passiert?
    description: Bitte beschreibe so gut es geht, was passiert ist.
    placeholder: Erzähle uns, was du gesehen hast!
  validations:
    required: true
- type: textarea
  id: how-to
  attributes:
    label: Wie können wir diesen Fehler nachstellen?
    description: Beschreibe bitte, wenn möglich, wie wir den Fehler reproduzieren
      können.
    placeholder: Beschreibe es so gut es geht.
  validations:
    required: true
- type: textarea
  id: expect
  attributes:
    label: Was hätte passieren sollen?
    description: Was hast du erwartet, was passieren sollte, als der Fehler auftrat.
    placeholder: Beschreibe es so gut es geht.
  validations:
    required: true
- type: textarea
  id: logs
  attributes:
    label: Bitte hänge deine log.txt an!
    description: Ziehe die Datei in das Textfeld, um die log.txt hoch zu laden oder
      verwende [Gist](https://gist.github.com/) oder [Pastebin](http://pastebin.com/).
    placeholder: Bitte füge deine log.txt von file path ("C:\\Users\\<USER_NAME>\\Documents\\My
      Games\\FarmingSimulator2025\\log.txt") an.
  validations:
    required: true
- type: textarea
  id: screenshots
  attributes:
    label: Screenshots
    description: Ziehe deine Screenshots in das Textfeld, um diese hochzuladen.
    placeholder: Wenn du Screenshots hast, die helfen dein Problem zu beschreiben,
      füge sie hier ein.
  validations:
    required: true
