name: Frage [DE]
description: Du hast eine Frage? Stell sie einfach!
labels:
- question
body:
- type: markdown
  attributes:
    value: 'Bitte benutze diese Vorlage, um deine Frage zu stellen!

      '
- type: dropdown
  id: mod-version
  attributes:
    label: Version
    description: Welche Enhanced Livestock Version verwendest du?
    options:
    - '0'
    - 1.0.0.0
    - 1.1.0.0-beta1
    default: 2
  validations:
    required: true
- type: dropdown
  id: spmp
  attributes:
    label: SP/MP
    description: Spielst du im SP oder MP?
    options:
    - SP (Singleplayer)
    - MP (Multiplayer)
    - egal
    default: 0
  validations:
    required: true
- type: textarea
  id: question
  attributes:
    label: Wie lautet deine Frage?
    description: Frage
    placeholder: Frage
  validations:
    required: true
- type: textarea
  id: screenshots
  attributes:
    label: Screenshots
    description: Ziehe deine Screenshots in das Textfeld, um diese hochzuladen.
    placeholder: Wenn du Screenshots hast, die helfen dein Frage zu beschreiben, füge
      sie hier ein.
  validations:
    required: false
